### ISSUE TITLE
Parcel Plugin Dart

### ISSUE THREAD

**Issue by neutrino2211** [parcel-bundler/awesome-parcel#51]
New plugin  for dartlang published on npm and it's pretty good. The github repo also has an example 

https://github.com/neutrino2211/parcel-plugin-dart

https://www.npmjs.com/package/parcel-plugin-dart

**Comment by DeMoorJasper** [comment]
Could you open up a PR for this?

**Comment by neutrino2211** [comment]
Here you go #52
