### ISSUE TITLE
@rfgamaral/parcel-plugin-typings-for-css-modules

### ISSUE THREAD

**Issue by rfgamaral** [parcel-bundler/awesome-parcel#72]
Ok, I'm biased, I know, but I just released this and I'm posting it here for your consideration.

It's not something new, I've actually borrowed two different implementations (credited on the README) and blended them together with a bit of extra salt.

I understand this is a **curated list**, no hard feelings if you don't feel like including it 🙂

📦 [`@rfgamaral/parcel-plugin-typings-for-css-modules`](https://github.com/rfgamaral/parcel-plugin-typings-for-css-modules)

**Comment by DeMoorJasper** [comment]
Just open a PR and it'll probably make it into the list :)
